### ISSUE TITLE
Error with package avaiable on multiple remotes: "No remote chosen to resolve matches for ..."

### ISSUE THREAD

**Issue by seigneurfuo** [imikado/dupotEasyFlatpak#11]
## Description
When an application is avaiable on multiple remotes (for exemple Flathub and Fedora remote), EasyFlatpak is unable to choose a remote and the application never get installed.

Easyflatpak version used: 2.17.3

![image](https://github.com/user-attachments/assets/37a1d32f-fff4-4a94-ba48-e668b62713ef)

I'm using Fedora Linux and by default, fedora already add a "Fedora" remote flatpak remote.

## CLI install for Flatseal

Flatpak CLI install of Flatseal:
```bash
flatpak install flatseal
Looking for matches…
Remotes found with refs similar to ‘flatseal’:

   1) ‘fedora’ (system)
   2) ‘flathub’ (system)
   3) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-3]:
```

## How to reproduce
- Use fedora Linux and try to install a software avaiable on multiple remotes (for exemple flatseal).

## Debug informations

Flatpak remotes list with CLI:
```bash
flatpak remotes

Name    Options
fedora  system,oci
flathub system
flathub user
```

## How to fix this error outside of Easyflatpak?
The user can remove the fedora remote.

**Comment by imikado** [comment]
ok thank for the bug report, i will fix it

**Comment by imikado** [comment]
i just publish a new release
can you test it ?
https://github.com/imikado/dupotEasyFlatpak/releases/tag/2.17.9

i will push it to flathub asap

**Comment by seigneurfuo** [comment]
The 2.17.9 version fixed the issue ! Thanks for the quick fix :)
