### ISSUE TITLE
Better integration and look

### ISSUE THREAD

**Issue by iza001** [imikado/dupotEasyFlatpak#14]
First of all, I loved it! It was the store we were waiting for for flatpaks!
Is there any possibility to use the GTK color scheme? for better integration.
It also happens that when I select the dark theme, when I start the app again, it is in light mode. 
When starting the application on the desktop, the icon is very large, ideally it would be centered and of a corresponding size. 
Again, amazing app!

**Comment by imikado** [comment]
hi,
I am working on a big new version, i fixed for the logo size at start
currently the dark/light mode is defined by the user, if you click to change, next time it will be at same mode (light/dark)

on the new versin i will permit to use "system dark/light mode" or "force" it to light/dark

**Comment by imikado** [comment]
I just deliver a new 3.0.0 version, you can test if it is better

**Comment by iza001** [comment]
Hello again!
Indeed the logo is excellent!
On fedora 41, using flatpak the screen is blank.
https://imgur.com/vTDraZR.png
Thanks for your great work!

**Comment by imikado** [comment]
A new version will be provided today: 3.1.3, i hope you will like the new updates

i just installed fedora 41 on my virtualbox, then install with flatpak easy flatpak,and i launched it without any issue..

**Comment by zilllaiss** [comment]
Love the new update btw. However, I currently don't fancy how the dark theme looks. The boxes' light blue don't blend well with the black background, and frankly it hurts my eyes, literally. 

I suggest going with a darker color for the boxes like this:
![gray](https://github.com/user-attachments/assets/a34e97d0-7402-4efb-a791-298a2cb3edb6)

I'm a dark theme user (as you can see from my screenshot), but I'm using the light theme because of that.

**Comment by imikado** [comment]
thanks for feedback
included in next release as other feedback
![Screenshot_20241222_111351](https://github.com/user-attachments/assets/184449d6-3251-4572-a648-147776134178)

**Comment by zilllaiss** [comment]
Great! Thanks for your hard work

**Comment by imikado** [comment]
can i close this issue ?

**Comment by zilllaiss** [comment]
I mean, you are the owner :) it's usually better to wait until release but it's up to you.

EDIT: I've just noticed the update. Great! I've got no complaint
