### ISSUE TITLE
support app size below 1MB

### ISSUE THREAD

**Issue by zilllaiss** [imikado/dupotEasyFlatpak#18]
Greetings. Today I discovered that if you have an app below 1MB, it will show as .00 format like the screenshot below:
![Screenshot_20241222_113323-1](https://github.com/user-attachments/assets/63b9aa18-3c4a-435e-86e6-72eda2ccff6d)

At first I thought the app size is 57MB, but then I noticed the small dot on the left size. It would be great to have a clearer indication for it to avoid confusion, like 0.57 MB or 559.6 KiB (as shown in Flathub).

**Comment by imikado** [comment]
hanks for feedback
![Screenshot_20241222_111003](https://github.com/user-attachments/assets/5dcf40fd-2d13-4b2f-bc68-5f7195c0156d)

**Comment by imikado** [comment]
can i close this issue ?

**Comment by zilllaiss** [comment]
Yeah. Seems like the update works. I will close it myself.
