### ISSUE TITLE
New theme feedback

### ISSUE THREAD

**Issue by zilllaiss** [imikado/dupotEasyFlatpak#19]
Greetings. First of all, I love your app. It's shows more information, faster, and more stable than KDE Discover and GNOME softwares.
That said, I do have some feedback regarding the looks.

First, the homepage has some questionable looks:
![Screenshot_20241222_114907-1](https://github.com/user-attachments/assets/558f4dac-ea89-44f1-8012-48791fecda56)

Then, the app listing. I think it's a little cramped:
![Screenshot_20241222_114319](https://github.com/user-attachments/assets/5e1e853d-07f9-430e-9770-e34a46b4ffdc)
Additionally, the app titles are too big here imo. But again, perhaps it's because of my screen size. Font size options or other density would be great, and I can't wait for it to come.

It would be nice to have them improved.

**Comment by imikado** [comment]
Hi
thanks for feedback
I will improve 
![Screenshot_20241222_110250](https://github.com/user-attachments/assets/3bd6c886-5cf7-4ce9-a5c2-0a0609ddb2dc)
![Screenshot_20241222_110453](https://github.com/user-attachments/assets/d01b9cc7-a79e-47e6-b954-40ff8b464105)

**Comment by zilllaiss** [comment]
It looks better now. Thanks.
