### ISSUE TITLE
Typos in AppStream description

### ISSUE THREAD

**Issue by AsciiWolf** [imikado/dupotEasyFlatpak#2]
There is just too many typos in the AppStream file description section:

>A simple flatpak store

flatpak -> Flatpak

>Install you flatpak application, and for some which need, we have recipe to help you ton install it better.

Maybe something like this could be better: `It will help you install Flatpak apps in a user-friendly way. We have recipes for some of them to install them even better.`

>For example, for Steam, it ask user to choose folder where he stores his games before installation

it ask user -> it asks the user
choose folder -> choose a folder
he stores his -> they store their
Missing dot at the end of the sentence.

**Comment by imikado** [comment]
thanks for feedback, il will fix in next version

**Comment by imikado** [comment]
Successfully updated, thanks for your help
https://flathub.org/apps/org.dupot.easyflatpak

**Comment by AsciiWolf** [comment]
Thanks for the quick fix! Maybe also consider changing the app name to "Easy Flatpak" (upper case Flatpak). :-)

**Comment by imikado** [comment]
I updated in my source code (https://github.com/imikado/dupotEasyFlatpak/commit/8e1a56b3bd6e78f27565f282b2475ac5bf08a44b),
 il will put it in next release with other features/fix
 
 don't hesitate to give feedbacks

for my information: how do you know this application ? and do you install it with flatpak/flathub or via .deb/.rpm ?

**Comment by AsciiWolf** [comment]
>for my information: how do you know this application ? and do you install it with flatpak/flathub or via .deb/.rpm ?

I discovered it on Flathub. :)

**Comment by AsciiWolf** [comment]
By the way, there are still typos in the README:

**Comment by AsciiWolf** [comment]
By the way, there are still typos in the [README](https://github.com/imikado/dupotEasyFlatpak?tab=readme-ov-file#dupot-easy-flatpak):

"Flatpak interface store."
->
"Flatpak store interface."

"This application help you to install your flatpak and for some of them, help you to install it."
->
"This application will help you install Flatpak apps in a user-friendly way. We have recipes for some of them to install them even better."
