### ISSUE TITLE
great job and request feature

### ISSUE THREAD

**Issue by DOOMMARINE117** [imikado/dupotEasyFlatpak#4]
is it possible to add a way to make searching for programs similar gnome software.com.com?

otherwise great setup and look. 

just a little buggy, but good

**Comment by imikado** [comment]
Hi,
Not for the moment, i will continue ton invest my time on this project and on my games development

"Little buggy" ? can you tell me bug list to help me to fix it quickly ?

**Comment by DOOMMARINE117** [comment]
> Hi, Not for the moment, i will continue ton invest my time on this project and on my games development
> 
> "Little buggy" ? can you tell me bug list to help me to fix it quickly ?

its a lttle rough when its trying to load the programs

**Comment by imikado** [comment]
The first launch would take more time to launch,( it has to unarchive/install the database  + application's icons)
but launch after should be quicker no ?
For information, each new version, i force the reinstallation of the database (to avoid any incompatibility with the new version)

**Comment by DOOMMARINE117** [comment]
> The first launch would take more time to launch,( it has to unarchive/install the database + application's icons) but launch after should be quicker no ? For information, each new version, i force the reinstallation of the database (to avoid any incompatibility with the new version)

i see, they go pretty quick compared  to gnome software

are the updates automatically installed?

**Comment by imikado** [comment]
if you installed it with flatpak, it will receive each update yes
You can see we are currently on 2.8.0, i'm working on next release

**Comment by DOOMMARINE117** [comment]
> if you installed it with flatpak, it will receive each update yes You can see we are currently on 2.8.0, i'm working on next release

cool.
