### ISSUE TITLE
Recipe for OBS Studio

### ISSUE THREAD

**Issue by martialgallorini** [imikado/dupotEasyFlatpak#7]
Hi,

I don't really know if there is a recipe type solution for this, but i stopped using the flatpak OBS solution because as a containerized app it won't have access to the external drivers installed on the host. 

In my case, i have Backmagic drivers installed in order to use Thunderbolt or PCIe capture cards. OBS can see the devices when installed via deb or from the repos but not when using flatpak.

If a recipe can allow this i think it can be really useful.

Thanks !

**Comment by imikado** [comment]
Hi
to check if it works
can you do this command line to check if it works with your obs studio via flatpak
flatpak override --user com.obsproject.Studio --filesystem=/path/to/your/external/driver

If it works i will create a recipe for it

**Comment by martialgallorini** [comment]
hi,

sorry for the delay, i was out of office.
I tried to override what i think drivers would be but i am not sure.
Blackmagic drivers are compiled and installed from source as Kernel drivers (DKMS)
Not sure if this works the same... anyway, no luck so far

**Comment by imikado** [comment]
ok, so no recipe for the moment. if you find the override aciton, i will create it

for the moment i close this issue
