### ISSUE TITLE
mise à jour non-détectée

### ISSUE THREAD

**Issue by julien9808** [imikado/dupotEasyFlatpak#8]
Bonjour,
L'application m'indique qu'il n'y a pas de mise à jour. Or si je lance la commande "flatpak update" sur le terminal, voici ce que j'obtiens : 

Looking for updates…
Required runtime for org.torproject.torbrowser-launcher/x86_64/stable (runtime/org.kde.Platform/x86_64/5.15-24.08) found in remote flathub
Do you want to install it? [Y/n]: y

        ID                                            Branch                Op            Remote            Download
 1.     org.kde.Platform.Locale                       5.15-24.08            i             flathub           < 401,4 Mo (partial)
 2.     org.kde.Platform                              5.15-24.08            i             flathub           < 372,7 Mo
 3.     org.torproject.torbrowser-launcher            stable                u             flathub             < 9,1 Mo
 4.     org.telegram.desktop                          stable                u             flathub            < 91,8 Mo

Proceed with these changes to the system installation? [Y/n]: 

Merci pour l'application !

**Comment by imikado** [comment]
Bonjour,
Pour information, pour savoir si il y a des mises à jour j execute la commande suivante:
`flatpak remote-ls --updates --columns=application,version`
Et je filtre par rapport aux applications présentes dans le catalogue d'application

Est-ce que vous utilisez la dernière version de l'application ? la dernière étant la 2.17.2 ?

**Comment by julien9808** [comment]
j’utilise bien la version 2.17.2, 
La commande citée ci-dessus me renvoie : 
Application ID                                Version
org.dupot.easyflatpak                         2.17.3
org.telegram.desktop                          5.7.2
org.torproject.torbrowser-launcher            0.3.7

Dans Easyflatpak, je ne vois que la version 2.17.3 en mise à jour. 
![Capture d’écran du 2024-11-14 18-02-53](https://github.com/user-attachments/assets/a98a4dcb-75c0-47c5-bb26-5b6d02fd1f5f)

**Comment by imikado** [comment]
j'ai fini par trouver le soucis, dispo dans prochaine release 
https://github.com/imikado/dupotEasyFlatpak/releases/tag/2.17.4

Vous avez installé par quel biais ? .deb,.rpm ou flatpak ? 
je conseille flatpak pour avoir les mises à jour au fil de l'eau

**Comment by julien9808** [comment]
Alors j'ai mis à jour easyflatpak (2.17.4) via flatpak, et là je vois maintenant bien les nouvelles mises à jour. 

Par contre j'ai maintenant  un soucis de fenêtrage, plus de barre de titre, je vous mets l'impression d'écran. (je suis sous wayland et gnome pour info)


![Capture d’écran du 2024-11-16 08-48-18](https://github.com/user-attachments/assets/97372bbf-0351-4af3-8b58-a1b1c92dcf13)

**Comment by imikado** [comment]
Hi
sorry for the bug, (we test only on x11 without bug)
can you test this version ?
https://github.com/imikado/dupotEasyFlatpak/releases/tag/2.17.6

**Comment by julien9808** [comment]
J'ai testé la version 2.17.6 mais aucun changement

**Comment by imikado** [comment]
je viens de faire une version pour retablir la gestion des fenetres
suis revenu en arrière pour la gestion des mises à jour : en utilisant commit vs version ça reglait sur ton cas et ça créérait une regression sur d'autre

je t'invite a tester cette version pour regler le soucis de windows manager
https://github.com/imikado/dupotEasyFlatpak/releases/tag/2.17.9

poru les updates, je regarde pour utiliser la commande flatpak update pour avoir les infos
mais moins facile à parser que ma commande `flatpak remote-ls`

**Comment by imikado** [comment]
nouvelle version basée sur flatpak update
https://github.com/imikado/dupotEasyFlatpak/releases/tag/2.17.10

**Comment by julien9808** [comment]
J'ai fais la mise à jour à la version 2.17.10. J'ai de nouveau la fenêtre qui s'affiche correctement mais 0 mises à jour de disponible, or la commande  flatpak remote-ls --updates --columns=application,version revoie 

com.github.jeromerobert.pdfarranger            1.11.1
org.freefilesync.FreeFileSync                  13.8
org.telegram.desktop                           5.7.2
org.torproject.torbrowser-launcher             0.3.7

**Comment by imikado** [comment]
Vous pouvez faire la mise à jour en 2.18.0, ça devrait etre mieux
desormais je m'appuie sur le retour de la commande flatpak update

mise à jour dispo via flatpak maintenant, sinon
https://github.com/imikado/dupotEasyFlatpak/releases/tag/2.18.0

**Comment by julien9808** [comment]
La version 2.18.0 ne m'affiche pas plus de mise à jour (0).
Par contre, lorsque je lance "flatpak update" j'obtiens une première demande ou il faut que je réponde avant de poursuivre les autres mises à jours, le soucis viendrait peut-être de là ?

_Looking for updates…
Required runtime for org.torproject.torbrowser-launcher/x86_64/stable (runtime/org.kde.Platform/x86_64/5.15-24.08) found in remote flathub
Do you want to install it? [Y/n]:_

**Comment by imikado** [comment]
oui c est ptete lié en effet

**Comment by imikado** [comment]
tu as pu retester depuis ?
La dernière version 2.19.0 permet en plus d'un seul bouton de tout updater

**Comment by julien9808** [comment]
Tout semble fonctionner pour les mises à jour.

**Comment by julien9808** [comment]
Ce jour, seule VLC est détectée comme mise à jour via Easy Flatpak, mais lorsque je lance flatpak update : 

>  1.     org.gnome.Platform.Locale                              46                  u          flathub         < 379,0 Mo (partial)
>  2.     org.gnome.Platform                                     46                  u          flathub         < 363,8 Mo
>  3.     org.kde.WaylandDecoration.QAdwaitaDecorations          5.15-23.08          u          flathub         < 955,5 ko
>  4.     org.kde.WaylandDecoration.QAdwaitaDecorations          5.15-24.08          u          flathub         < 981,5 ko
>  5.     org.kde.WaylandDecoration.QAdwaitaDecorations          6.7                 u          flathub           < 1,2 Mo
>  6.     org.videolan.VLC.Locale                                stable              u          flathub          < 14,1 Mo (partial)
>  7.     org.videolan.VLC                                       stable              u          flathub          < 39,1 Mo

Proceed with these changes to the system installation? [Y/n]: 
![Capture d’écran du 2024-11-30 08-58-24](https://github.com/user-attachments/assets/8641e976-05ea-40c3-805a-170cea0681ec)

**Comment by imikado** [comment]
hi,
That is "normal", because i filter to only application i have on flathub

I'm working on a big new version, i note to display this kind of "not application" package to update

**Comment by imikado** [comment]
J'ai livré une nouvelle version 3.0.0 dernièrement, vous pouvez check si c'est mieux désormais ?

**Comment by julien9808** [comment]
Ca fonctionne bien, tout est pris en compte maintenant, merci !

**Comment by imikado** [comment]
cool,je cloture donc cette issue
