### ISSUE TITLE
Feature idea: Automatic language selection based on user language.

### ISSUE THREAD

**Issue by seigneurfuo** [imikado/dupotEasyFlatpak#9]
First of all: Thank you for this great tool!

Here's an idea for a feature that would be interesting to implement.

On first launch, the user language is detected from environment variables and the EasyFlatpak user interface language is changed to match the user's local language (if available). If not, fallback to English.

**Comment by imikado** [comment]
hi,
i am working on new big version, i will see in settings to allow for language as for dark/light mode to use system parameter or to override it

**Comment by imikado** [comment]
I just added this on the latest version, tell me if it works fine on your side

**Comment by seigneurfuo** [comment]
Thank you for taking the time to implement this feature.
I had tested by editing the ```LANG=``` env variable and works fine for autodetection of French and Italian.

**Comment by imikado** [comment]
Hi,
Thanks for testing

Yes, when i can implement user needs, i invest time to do it, and the application progress
I'm working on new features coming soon, stay tuned, i hope you will like it :)

i close this issue
